name: Infra - Run Terraform

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      directory:
        required: true
        type: string
      state_bucket_name:
        required: true
        type: string
      state_key:
        required: true
        type: string
      apply_changes:
        default: false
        type: boolean

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_aws_region: ${{ vars.AWS_REGION }}
  TF_VAR_environment: ${{ inputs.environment }}

jobs:
  terraform:
    defaults:
      run:
        working-directory: ${{ inputs.directory }}
    runs-on: ubuntu-latest

    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true # Ensure submodules are initialized and updated

      - name: Initialize submodules
        run: git submodule update --init --recursive

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -backend-config="bucket=${{ inputs.state_bucket_name }}" -backend-config="key=${{ inputs.state_key }}" -backend-config="region=${{ vars.AWS_REGION }}"

      - name: Terraform format
        id: fmt
        run: terraform fmt -check

      - name: Terraform validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan -input=false

      - name: Terraform Apply
        if: inputs.apply_changes == true
        run: terraform apply tfplan
