name: Lambdas - Deploy lambdas using SAM

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      directory:
        required: true
        type: string

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ vars.AWS_REGION }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.directory }}

    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: Setup SAM
        uses: aws-actions/setup-sam@v2

      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: Build SAM application
        run: pnpm build

      - name: Deploy SAM application
        run: |
          sam deploy \
            --stack-name ${{ inputs.environment }}-margoule \
            --s3-bucket ${{ vars.S3_SAM_BUCKET }} \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              Stage=${{ inputs.environment }} \
              S3LinkedinScrapBucket=${{ vars.S3_LINKEDIN_SCRAP_BUCKET }} \
              LambdaRoleName=${{ vars.LAMBDA_ROLE_NAME }} \
              MargouleDiscordWebhookUrl=${{ secrets.MARGOULE_DISCORD_WEBHOOK_URL }} \
            --region ${{ vars.AWS_REGION }} \
